### PR TITLE
Add German language support

### PR DESCRIPTION
**Pull request by abirke**

### CODE REVIEW

**Comment by sakhnevych** [comment]
Hi @abirke , will it be correct to use the 3 letter names?
There is a conflict with other languages if we use 2 letters. I don't want to break backwards compatibility.

- Mon (Montag)
- Die (Dienstag)
- Mit (Mittwoch)
- Don (Donnerstag)
- Fre (Freitag)
- Sam (Samstag)
- Son (Sonntag)

**Comment by sakhnevych** [comment]
Here is it: https://github.com/sakhnevych/calendar-view/blob/master/calendar_view/config/i18n.py#L29

I am ready to publish the release if it looks OK.

**Comment by sakhnevych** [comment]
Published. Please write here if my changes to the German localisation are not correct.

**Comment by abirke** [comment]
Hi @sakhnevych,

sorry to keep you waiting. The three-letter abbreviations are pretty uncommon, I think. For parsing, however, I am not sure if a German translation is even necessary. Personally, I don't have any use-case for the translated parsing part.

Would you be okay with using the two-letter abbrevations and not supporting German in the parsing?

Otherwise, I guess I can live with the current solution.

Thanks, anyway!

André

**Comment by sakhnevych** [comment]
@abirke , I have updated the code and released the latest version with two-letter abbreviations and a three-letter for parsing as a workaround (I think this is not a popular feature, and it is different from the name on the image anyway).

I will rely on your German language skills. Thanks for the pull request!

**Pull request merged**
